### ISSUE TITLE
项目里的证书不合标

### ISSUE THREAD

**Issue by xipki** [guanzhi/GM-Standards#1]
为了不引起不便，请私下交流。 可以联系我。具体联系方式见我的项目https://github.com/xipki/xipki/

**Comment by xipki** [comment]
另标准GMT 0015也有错误

**Comment by guanzhi** [comment]
标准文本是正式标准纸质版的扫描件，请问有什么错误？
证书主要是从国内正式CA网站上收集的，如果有什么问题请直接发在这里，谢谢

**Comment by xipki** [comment]
1. 是标准本身有误，不是您的扫描件。
2. 已经和CA厂商联系了，谢谢
